### ISSUE TITLE
Warnings of deprecated libraries upon Docker build vue_apps

### ISSUE THREAD

**Issue by hickst** [oci-labs/rapid-stack#3]
```
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
```

**Comment by dorian-yeager** [comment]
Unfortunately this is not a result of this repo.  These warnings are coming from npm install itself.  Please see the issue below:
https://github.com/11ty/eleventy/issues/1178

I'm certain they will correct this quickly.  However, you can specify an earlier version of npm in the dockerfile if you wish.
Thank you for your support and bringing this to my attention.

**Comment by dorian-yeager** [comment]
These warnings unfortunately do not originate with my code.  They appear to come from the npm install of vue/cli.  Hopefully it is remedied soon.

**Comment by dorian-yeager** [comment]
Upgraded project to use Vue 3.  I am no longer seeing any issues.
