### ISSUE TITLE
version compatibility

### ISSUE THREAD

**Issue by bitsnaps** [oci-labs/rapid-stack#4]
Hi, I just wonder about compatibility in the future release, coz we're using the latest version for each build, how can we guarantee the future release is compatible with each layer stack ?

**Comment by dorian-yeager** [comment]
This is a pretty high level question so I have to answer generically.  The layers of the stack are a back end store (mongo), a web service layer(python/flask) and a front end (vue).  These layers communicate over long established protocols and are in no way tightly coupled.  That is why you could easily change what you use as a front end application so long as it can make restful calls to the web services.

The only real problem with keeping the latest version of all things is that occasionally the docker containers will fail to build.  For example, Alpine just moved pip3 to its own package.  In that case I have to update the dockerfile.

If it were the case that a new version of a dependency broke something in a significant way the solution would be to fix that dependency at a prior version until a solution is found.

If you do not want to keep the latest versions of the tool chain the answer is to update the docker files of your personal copy of the project to reflect the versions of the dependencies you would like to use.
